services:
  docs:
    image: practice_project_local_docs
    container_name: practice_project_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./practice_project:/app/practice_project:z
    ports:
      - '9000:9000'
    command: /start-docs
